### ISSUE TITLE
Doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by jkoop** [lamyj/sneakersync#6]
(Actually, I'm using [Linux Mint 20](http://linuxmint.com/) which is very much based on Ubuntu 20.04)

I installed sneakersync with
```
sudo apt install python3-pip
pip3 install sneakersync
PATH=$PATH:'/home/username/.local/bin'
```
and created a config file `sneakersync.cfg` at `/media/username/250GB Drive/sneakersyncTest/`:
```
modules:
  - root: /home/username/Documents
```
and ran sneaksync, but it failed:
```
username@hostname:~$ sneakersync send '/media/username/250GB Drive/sneakersyncTest/'
/home/username/.local/lib/python3.8/site-packages/sneakersync/operations.py:75: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(fd)
Sending /home/username/Documents
rsync: --crtimes: unknown option
rsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]
ERROR: Could not send module /home/username/Documents: 
b'rsync: --crtimes: unknown option\nrsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]\n'
```

I think I did everything right. Ideas?

**Comment by lamyj** [comment]
Sneakersync is pretty much untested outside macOS, but the current HEAD (c09c45d) should fix your issue. Can you re-run your test from the latest source code (clone if needed, then from the source directory `pip3 install --upgrade ./`)

**Comment by jkoop** [comment]
I reran my test, and it failed again.
```
username@hostname:~$ sneakersync send '/media/username/250GB Drive/sneakersyncTest'/
Sending /home/username/Documents
rsync: --fileflags: unknown option
rsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]
ERROR: Could not send module /home/username/Documents: 
b'rsync: --fileflags: unknown option\nrsync error: syntax or usage error (code 1) at main.c(1596) [client=3.1.3]\n'
```
Teamwork! I test; you fix. lol

**Comment by lamyj** [comment]
No Python knowledge required, I forgot another macOS-specific option. Current HEAD (ebc151c) runs in my Debian 10 (Buster) VM on a simple use-case. Unless you are using extended attributes, you should be good to go (xattr tests still fail with an *Operation not supported error*, need to investigate this).

**Comment by jkoop** [comment]
Success! It works with the following `sneakersync.cfg`:
```
modules:
  - root: /home/username/Documents
```
No errors reported.
